# Build settings
markdown: kramdown
permalink: pretty
baseurl: "/cvsite"

# Collections
collections:
  pages:
    output: true
    permalink: /:path/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default" 